version: "3.9"

services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"

  execution-service:
    # build:
    #   context: .
    #   dockerfile: dockerfile.dev
    image: run-code-server-execution-service
    working_dir: /app
    volumes:
      - .:/app
      # - /app/node_modules
    command: npm run dev
    environment:
      REDIS_URL: redis://redis:6379
    depends_on:
      - redis
